# Generated by Django 6.1 on 2026-08-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_management', '0002_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
