# Generated by Django 6.1 on 2026-08-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_management', '0003_alter_instructor_instructor_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='availability',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instruments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
