# Generated by Django 6.1 on 2026-08-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_management', '0004_alter_instructor_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='availability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instruments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
