# Generated by Django 6.1 on 2026-08-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_management', '0006_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_months', models.PositiveIntegerField(default=1)),
                ('total_lessons', models.PositiveIntegerField(default=0)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructors', models.ManyToManyField(blank=True, related_name='courses', to='students_management.instructor')),
            ],
        ),
    ]
