# Generated by Django 6.1 on 2026-08-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_management', '0008_lessontype_remove_course_duration_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
