# Generated by Django 6.1 on 2026-08-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_management', '0009_lessonduration'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('institute', 'Institute'), ('online', 'Online'), ('home_visit', 'Home Visit')], max_length=30, unique=True)),
                ('additional_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
