# Generated by Django 6.1 on 2026-08-31 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_management', '0010_lessonmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='OMR', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='students_management.course')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_pricing', to='students_management.lessonduration')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_pricing', to='students_management.lessontype')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_pricing', to='students_management.lessonmode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'lesson_type', 'duration', 'mode', 'level'), name='unique_course_pricing')],
            },
        ),
    ]
