# Generated by Django 6.1 on 2026-08-31 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_management', '0012_coursepackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='OMR', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='students_management.coursepackage')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_prices', to='students_management.coursepricing')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('package', 'pricing'), name='unique_package_pricing')],
            },
        ),
    ]
