# Generated by Django 6.1 on 2026-09-01 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_management', '0014_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='student',
        ),
        migrations.AddField(
            model_name='appointment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='students_management.enrollment'),
        ),
        migrations.AddField(
            model_name='course',
            name='selected_lesson_durations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='selected_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='selected_modes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='selected_packages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
