# Generated by Django 6.1 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students_management", "0015_remove_appointment_student_appointment_enrollment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="registration_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
