# Generated by Django 6.1 on 2026-09-02

from django.db import migrations, models


CATEGORIES = [
    "Piano", "Acoustic Guitar", "Electric Guitar", "Classical Guitar",
    "Violin", "Drums", "Vocals", "Keyboard", "Flute", "Saxophone",
    "Cello", "Ukulele", "Music Production", "Music Theory",
]


def add_default_categories(apps, schema_editor):
    Category = apps.get_model("students_management", "Category")
    for name in CATEGORIES:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [("students_management", "0016_enrollment_registration_fee")]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"], "verbose_name_plural": "categories"},
        ),
        migrations.RunPython(add_default_categories, migrations.RunPython.noop),
    ]
