# Generated by Django 6.1 on 2026-09-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_management', '0017_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
