# Generated by Django 6.1 on 2026-09-04 13:45

import django.db.models.deletion
from django.db import migrations, models


def assign_existing_records_to_locations(apps, schema_editor):
    Location = apps.get_model('students_management', 'Location')
    Student = apps.get_model('students_management', 'Student')
    Instructor = apps.get_model('students_management', 'Instructor')
    Enrollment = apps.get_model('students_management', 'Enrollment')
    Appointment = apps.get_model('students_management', 'Appointment')

    # Preserve existing branch labels by creating one location per name.  Rows
    # without a branch are assigned to a safe default so they remain visible.
    default_location, _ = Location.objects.get_or_create(
        code='MAIN', defaults={'name': 'Main Location'}
    )
    locations = {'': default_location}

    def location_for(name):
        name = (name or '').strip()
        if name not in locations:
            code_base = ''.join(ch for ch in name.upper() if ch.isalnum())[:24] or 'LOCATION'
            code = code_base
            suffix = 2
            while Location.objects.filter(code=code).exists():
                code = f'{code_base[:24]}{suffix}'
                suffix += 1
            locations[name], _ = Location.objects.get_or_create(code=code, defaults={'name': name})
        return locations[name]

    for model in (Student, Instructor, Appointment):
        for item in model.objects.filter(location__isnull=True):
            item.location = location_for(item.branch_name)
            item.save(update_fields=['location'])

    # Enrollments predate the location field; inherit their student's location.
    for enrollment in Enrollment.objects.filter(location__isnull=True).select_related('student'):
        enrollment.location = enrollment.student.location or default_location
        enrollment.save(update_fields=['location'])


def reverse_assign_existing_records(apps, schema_editor):
    # Location associations are intentionally retained when rolling back.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('students_management', '0019_student_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='branch_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='students_management.location'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students_management.location'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='students_management.location'),
        ),
        migrations.AddField(
            model_name='student',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students_management.location'),
        ),
        migrations.RunPython(assign_existing_records_to_locations, reverse_assign_existing_records),
    ]
