# Generated by Django 6.1 on 2026-09-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_management', '0023_location_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('requested', 'Requested'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
    ]
