# Generated by Django 6.1 on 2026-09-04 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0001_initial'),
        ('students_management', '0020_location_remove_course_branch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='students_management.location'),
        ),
    ]
