# Generated by Django 6.1 on 2026-09-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0002_staff_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
